### ISSUE TITLE
Calling returned function immediately gives a syntax error

### ISSUE THREAD

**Issue by mcarter6061** [dcutting/Song#68]
For a function which returns a function,  calling the returned function immediately fails.  Binding the returned function to a variable and calling that in a second step works.
```
> lessThan(x) = |y| y < x
> lessThan5 = lessThan(5)
> lessThan5(4)
Yes
> lessThan(5)(4)
💥  syntax error: (4)
```

**Comment by dcutting** [comment]
Fixed in v0.5.0.
